[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/build",
  "cp -r frontend/build/* backend/build/"
]

[start]
cmd = "python3 backend/app.py"
